### ISSUE TITLE
Regression 🚨 Unfusing LoRAs is broken after the first fuse/unfuse operation

### ISSUE THREAD

**Issue by apolinario** [huggingface/diffusers#5000]
### Describe the bug

For some combination of LoRAs, if I try to `pipe.unfuse_lora()`, after a LoRA has already been fused/unfused to the pipe, I get an error: 

```py
import torch
from diffusers import StableDiffusionXLPipeline
  
pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
).to("cuda")

#Fuse/unfuse first LoRA  
pipe.load_lora_weights("joachimsallstrom/aether-cloud-lora-for-sdxl")
pipe.fuse_lora()
pipe.unfuse_lora()

#Now it would be expected that the the LoRA has been unfused and `pipe` in the its original state, however...

#Fuse/unfuse second LoRA
pipe.load_lora_weights("jbilcke-hf/sdxl-zelda64")
pipe.fuse_lora()
pipe.unfuse_lora() #errors out
```

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-13-50a0e2ae069f>](https://localhost:8080/#) in <cell line: 9>()
      7 pipe.load_lora_weights("jbilcke-hf/sdxl-zelda64")
      8 pipe.fuse_lora()
----> 9 pipe.unfuse_lora()
[/usr/local/lib/python3.10/dist-packages/diffusers/models/lora.py](https://localhost:8080/#) in _unfuse_lora(self)
    211         dtype, device = fused_weight.dtype, fused_weight.device
    212 
--> 213         w_up = self.w_up.to(device=device).float()
    214         w_down = self.w_down.to(device).float()
    215 

AttributeError: 'NoneType' object has no attribute 'to'
```

This is not expected. The expectation is that, after the first `pipe.unfuse_lora()` the `pipe` is in an original state. This issue shows however that something is changing.

The proof that this is what is happening is that, If I try to fuse/unfuse the LoRA that is erroring out without first loading the `joachimsallstrom/aether-cloud-lora-for-sdxl`, it works perfectly: 
```py
pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
).to("cuda")

pipe.load_lora_weights("jbilcke-hf/sdxl-zelda64")
pipe.fuse_lora()
pipe.unfuse_lora()
```

So the issue only arises after first fuse/unfuse `joachimsallstrom/aether-cloud-lora-for-sdxl` and then try to fuse/unfuse `jbilcke-hf/sdxl-zelda64`

### Reproduction

Repro Colab: https://colab.research.google.com/drive/1QH1J3oWJwnIx7bnwGM3EOKX9hOd8I7ZU

### System Info

diffusers `main` latest commit `1f948109b80b8181b06aa6fc39f27a908b27322d`

### Who can help?

@patrickvonplaten , @sayakpaul

**Comment by apolinario** [comment]
Issue not reproducible, it is actually working. My bad

**Comment by apolinario** [comment]
Okay, I found a stable repro

**Comment by patrickvonplaten** [comment]
Nice I can repro. I think [this](https://github.com/huggingface/diffusers/pull/5003) should fix it.

Can you give it a try @apolinario if it works, I can merge

**Comment by apolinario** [comment]
It works!

**Comment by apolinario** [comment]
This seems to have regressed as of `0.21.3`, you can check in the repro notebook the error:
 ```bash
 [/usr/local/lib/python3.10/dist-packages/diffusers/models/lora.py](https://localhost:8080/#) in _unfuse_lora(self)
    211         dtype, device = fused_weight.dtype, fused_weight.device
    212 
--> 213         w_up = self.w_up.to(device=device).float()
    214         w_down = self.w_down.to(device).float()
    215 

AttributeError: 'NoneType' object has no attribute 'to'
``` 
Is back. This was raised here as we were planning to use it on the Inference API: https://github.com/huggingface/api-inference-community/pull/334#issuecomment-1740683126

**Comment by patrickvonplaten** [comment]
No regression here, the issue is solved with https://github.com/huggingface/diffusers/pull/5003 as far as I can see

**Comment by apolinario** [comment]
True, I missed the fact that this didn't get into the latest release
