### PR TITLE
fix: correct AttributeError in TangentialCFG and NameError in FrequencyDecoupledGuidance

### PR DESCRIPTION
**Pull request by Ricardo-M-L**
## Summary

Fixes two functional bugs in the experimental guiders module, both introduced in #11311 (Modular Diffusers Guiders):

### Bug 1: `TangentialClassifierFreeGuidance.is_conditional` — AttributeError

The `is_conditional` property references `self._num_outputs_prepared`, which does not exist on the class or its base class `BaseGuidance`. Every other guider uses `self._count_prepared` (defined and managed by `BaseGuidance`). Accessing `is_conditional` on a `TangentialClassifierFreeGuidance` instance raises:

```
AttributeError: 'TangentialClassifierFreeGuidance' object has no attribute '_num_outputs_prepared'
```

**Fix:** Replace `self._num_outputs_prepared` with `self._count_prepared`.

### Bug 2: `FrequencyDecoupledGuidance.forward` — NameError / wrong pyramid level

In the `forward` method's loop over pyramid levels, the `else` branch (when FDG is disabled for a level) appends `pred_cond_freq` to the guided pyramid. However, `pred_cond_freq` is only assigned inside the `if` branch. This causes:

- **NameError** if the very first pyramid level has FDG disabled (variable never assigned)
- **Silent wrong results** if a prior level assigned it — the wrong level's frequency data gets used

**Fix:** Replace `pred_cond_freq` with `pred_cond_pyramid[level]` to correctly reference the current level's conditional prediction.

## Test plan

- [x] Verified `_num_outputs_prepared` is not defined anywhere in the codebase; `_count_prepared` is the correct attribute used by all other guiders
- [x] Verified `pred_cond_freq` is only assigned inside the `if` branch, confirming the `else` branch will fail or use stale data
- [x] Checked no existing open PRs address these issues

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by Ricardo-M-L** [comment]
Friendly bump — this is a tiny (+2/-2 across 2 files) crash fix: `TangentialCFG` hits `AttributeError` and `FrequencyDecoupledGuidance` hits `NameError` due to a referenced-but-undefined symbol. Both are outright crashes when the classes are instantiated. Happy to rebase if needed — thanks for any review time you can spare.
