### ISSUE TITLE
Error "'Timesteps' object has no attribute 'scale'" on the 0.30.x version while using my own diffusion model

### ISSUE THREAD

**Issue by Vasasasasa** [huggingface/diffusers#9613]
### Describe the bug

I use my own pretrained model to generate images. When I use diffusers 0.29.2 everything is fine, but when I updated it to 0.30.0, for whatever reason, it just stopped working.
<img width="809" alt="Screenshot 2024-10-09 at 1 28 30 PM" src="https://github.com/user-attachments/assets/b1103560-ea3c-4464-939e-f534f267b6f9">
<img width="1575" alt="Screenshot 2024-10-09 at 1 35 54 PM" src="https://github.com/user-attachments/assets/23ce459e-0f87-4df8-8b39-c60f27de1508">
Link to the model: https://drive.google.com/file/d/1TaqRPQX9M7t0tFcZT7y71r-koh38qUs6/view?usp=drive_link

### Reproduction

device = torch.device("cuda:0" if (torch.cuda.is_available() and 1 > 0) else "cpu")
path='/Users/aleksejmackan/Downloads/dif1.h5'
model = torch.load(path,map_location=torch.device(device),weights_only=False)
timesteps = torch.linspace(0, 999, 8).long()
scheduler = DDIMScheduler(num_train_timesteps=1000,beta_start=0.001, beta_end=0.02)
pipeline = DDPMPipeline(unet=model, scheduler=scheduler).to(device)
sample = pipeline(batch_size=1).images
show_images(sample, nrows=1)

### Logs

```shell
AttributeError                            Traceback (most recent call last)
Cell In[2], line 7
      5 scheduler = DDIMScheduler(num_train_timesteps=1000,beta_start=0.001, beta_end=0.02)
      6 pipeline = DDPMPipeline(unet=model, scheduler=scheduler).to(device)
----> 7 sample = pipeline(batch_size=1).images
      8 show_images(sample, nrows=1)
      9 """
     10 image1_tensor= sample
     11 image1_numpy = image1_tensor.numpy()
   (...)
     41 ImageLoader.save_compare(image4_tensor, preds4, './scaled_images_compared/scaled_'+str(ik+3)+'_compare.png')
     42 """

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> 116         return func(*args, **kwargs)

File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/diffusers/pipelines/ddpm/pipeline_ddpm.py:114, in DDPMPipeline.__call__(self, batch_size, generator, num_inference_steps, output_type, return_dict)
    110 self.scheduler.set_timesteps(num_inference_steps)
    112 for t in self.progress_bar(self.scheduler.timesteps):
    113     # 1. predict noise model_output
--> 114     model_output = self.unet(image, t).sample
...
   1727     if name in modules:
   1728         return modules[name]
-> 1729 raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

AttributeError: 'Timesteps' object has no attribute 'scale'
```

### System Info

- 🤗 Diffusers version: 0.30.0
- Platform: macOS-15.1-arm64-arm-64bit
- Running on Google Colab?: No
- Python version: 3.11.4
- PyTorch version (GPU?): 2.4.0 (False)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.25.1
- Transformers version: 4.45.2
- Accelerate version: not installed
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.5
- xFormers version: not installed
- Accelerator: Apple M1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by a-r-r-o-w** [comment]
cc @yiyixuxu

**Comment by Vasasasasa** [comment]
Thanks! That
