### ISSUE TITLE
In version 0.20.0, StableDiffusionPipeline.from_single_file does not work.

### ISSUE THREAD

**Issue by dai-ichiro** [huggingface/diffusers#4667]
It worked fine in diffusers==0.19.3, but after updating to version 0.20.0, I got the following error.
### Logs
~~~
TypeError: StableDiffusionPipeline.__init__() got an unexpected keyword argument 'text_encoder_2'
~~~
### Reproduction
~~~python
from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_single_file(
    "sd_xl_base_1.0_0.9vae.safetensors",
    torch_dtype=torch.float16 
    ).to("cuda")

prompt = "a pretty woman"

image = pipe(prompt=prompt).images[0]

image.save("result.png")
~~~
### System Info
Windows 11
python: 3.10.11
diffusers: 0.19.3 and 0.20.0

**Comment by sayakpaul** [comment]
It should be `StableDiffusionXLPipeline`.
