### ISSUE TITLE
LoRA to Diffusers conversion script not working with models using SDXL 1.0 as base model

### ISSUE THREAD

**Issue by richiebailey74** [huggingface/diffusers#7483]
### Describe the bug

I am trying to convert .safetensors that are trained with LoRA using SDXL 1.0 as the base model to the Diffusers compatible format. I am running the conversion script convert_lora_safetensor_to_diffusers.py and the error I get is in the python logs below. The error is coming from line 55:
`curr_layer = curr_layer.__getattr__(temp_name)
`and this line has thrown similar errors for other SDXL 1.0 LoRA safetensors models as well, just seems to be different attributes the errors are thrown on when trying to extract attributes that the objects don't have.

The attribute error in the logs below: 
`AttributeError: 'CLIPTextModel' object has no attribute 'lora_te1_text_model_encoder_layers_0_mlp_fc1'`
The other attribute error I saw with another model: 
`AttributeError: 'UNet2DConditionModel' object has no attribute 'input_blocks_4_1_proj_in'`

### Reproduction

I am pulling the conversion script into my current directory using:
`wget https://raw.githubusercontent.com/huggingface/diffusers/v0.27.2/scripts/convert_lora_safetensor_to_diffusers.py
`
I am downloading the weights from civitAI into my current directory (https://civitai.com/models/259365/sdxl-chalkboarddrawing-lora)

The exact script I am running:
`python convert_lora_safetensor_to_diffusers.py --base_model_path stabilityai/stable-diffusion-xl-base-1.0 --checkpoint_path SDXL_ChalkBoardDrawing_LoRA_r8.safetensors --dump_path diffusers_objects/SDXL_ChalkBoardDrawing_LoRA_r8/`

### Logs

```shell
Traceback (most recent call last):
  File ".../models/convert_lora_safetensor_to_diffusers.py", line 55, in convert
    curr_layer = curr_layer.__getattr__(temp_name)
  File ".../.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'CLIPTextModel' object has no attribute 'lora_te1_text_model_encoder_layers_0_mlp_fc1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../models/convert_lora_safetensor_to_diffusers.py", line 125, in <module>
    pipe = convert(base_model_path, checkpoint_path, lora_prefix_unet, lora_prefix_text_encoder, alpha)
  File ".../models/convert_lora_safetensor_to_diffusers.py", line 62, in convert
    temp_name += "_" + layer_infos.pop(0)
IndexError: pop from empty list
```

### System Info

- `diffusers` version: 0.27.2
- Platform: macOS-12.6-arm64-arm-64bit
- Python version: 3.10.11
- PyTorch version (GPU?): 2.1.1 (False)
- Huggingface_hub version: 0.21.4
- Transformers version: 4.38.2
- Accelerate version: 0.28.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by asomoza** [comment]
is there a reason why you're trying to convert it? That script hasn't been updated in over a year, the conversion code I mean.

**Comment by sayakpaul** [comment]
You should directly use what @asomoza mentioned in https://github.com/huggingface/diffusers/issues/7483#issuecomment-2021775037.

**Comment by richiebailey74** [comment]
Awesome, I am a bit new to using diffusers so thank you for pointing me in the correct direction.
