### ISSUE TITLE
AttributeError: 'Linear' object has no attribute 'set_lora_layer'

### ISSUE THREAD

**Issue by aihao2000** [huggingface/diffusers#5919]
### Describe the bug

I use (ttps://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py to train lora and raise an error ```AttributeError: Linear' object has no attribute 'set_lora_layer```.

### Reproduction

training examples/text_to_image/train_text_to_image_lora.py

### System Info

- `diffusers` version: 0.24.0.dev0
- Platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.27
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@sayakpaul @patrickvonplaten

**Comment by aihao2000** [comment]
Solved after uninstalling peft.

**Comment by johnowhitaker** [comment]
Likewise.

**Comment by BenjaminBossan** [comment]
I did a quick search and indeed, there are 3 examples which call `set_lora_layer` unconditionally:

- `examples/text_to_image/train_text_to_image_lora.py` (reported here)
- `examples/dreambooth/train_dreambooth_lora.py`
- `examples/dreambooth/train_dreambooth_lora_sdxl.py`

The package code itself looks good though, all instances of `set_lora_layer` that I could find were guarded.

**Comment by sayakpaul** [comment]
@patrickvonplaten I had a chance to investigate the problem. We have:

https://github.com/huggingface/diffusers/blob/50a749e90990932d49556ee54a333278559722f3/src/diffusers/models/attention_processor.py#L176-#L179

In case `peft` is present we're relying on `nn.Linear`, instead of `LoRACompatibleLinear` (which is the right thing to do). However, our training scripts rely on `set_lora_layer()`. I am not sure there's any other way around for this other than just using `peft`. https://github.com/huggingface/diffusers/pull/5419 should solve all of these problems quite nicely.

**Comment by Johnson-yue** [comment]
how to fixed this bug , during training lora with script must uninstall peft but during inference , dependence peft ??? It is  a big problem for usage

**Comment by aihao2000** [comment]
@johnowhitaker You can try torch.load lora_weights file. Then use pipe.unet.load_attn_procs

**Comment by sayakpaul** [comment]
Can you elaborate what you mean?

**Comment by sayakpaul** [comment]
Honestly, I don't think we need to do that because we know that https://github.com/huggingface/diffusers/pull/5388 is going to be merged very very soon. So, any changes will soon become redundant and will need to be removed.

**Comment by patrickvonplaten** [comment]
The old scripts will still be used quite a bit I think. I'm sure that people will go back to use them as they don't want to update all their training scripts to PEFT yet. As it's an easy change I'd be in favor of adding it even if it might be there only for a week

**Comment by yashveer08** [comment]
Hii, I am facing the same issue, It was working good for me till yesterday that is 5/12/2023, and since today it is showing 'set_lora_layer' issue. Any update on this or how to resolve this issue?

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/6045

Does the above PR work?

**Comment by yashveer08** [comment]
I checked onto your branch from which the PR is raised and tried running through there. I got the same error.

`AttributeError: 'Linear' object has no attribute 'set_lora_layer'`

this is my launch command,

`!accelerate launch train_text_to_image_lora_sdxl.py \
  --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --train_data_dir="/kaggle/input/training-dataset-612" --caption_column="text" \
  --resolution=1024 --random_flip \
  --train_batch_size=1 \
    --checkpointing_steps=400 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --seed=42 \
  --output_dir="/kaggle/working/sd-lora-sdxl" \
  --gradient_checkpointing \
  --mixed_precision="fp16" \
  --num_train_epochs=100 \
  --push_to_hub \
    --hub_token $HF_TOKEN \
    --hub_model_id $REPO_ID \
    `
    
    Am I missing something becuase it was perfectly fine till yesterday.

**Comment by sayakpaul** [comment]
Can you shed some light on your environment? Versions, etc.? Do you have peft installed?

**Comment by sayakpaul** [comment]
Will investigate. Sorry for the trouble.

**Comment by sayakpaul** [comment]
@yashveer08 sorry about the delay. I think you would need to propagate the changes introduced in https://github.com/huggingface/diffusers/pull/6045 to the `train_text_to_image_lora_sdxl.py` script to be able to see if they resolve the problem. Could you try it and report once? 

Also note that with https://github.com/huggingface/diffusers/pull/5388/, this won't actually be needed. 

But we will just keep the PR open for respecting our users as @patrickvonplaten pointed out here:
https://github.com/huggingface/diffusers/issues/5919#issuecomment-1838258956. 

Does that make sense?

**Comment by Dr-Abishek** [comment]
> Solved after uninstalling peft.

How do I uninstall peft in a noteook environment such as colab or kaggle?

**Comment by satvikkk** [comment]
Hi, I am trying to run https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_dreambooth_lora_sdxl.py and getting the same error: **AttributeError: 'Linear' object has no attribute 'set_lora_layer'**. Since a lot of changes have been made since then, can you help me with what versions of diffusers, torch, xformers, torchvision, etc. should I use? I am mostly facing compatibility issues. If there are any changes to be made in the training script, can you mention that as well? I have tried running it with and without PEFT. Thanks!
@sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
You should make sure you are using the latest version of diffusers pulled from the `main` and then try again.
