### ISSUE TITLE
WanVACEPipeline does not work with low-noise stage only

### ISSUE THREAD

**Issue by vladmandic** [huggingface/diffusers#12410]
### Describe the bug

`WanVACEPipeline` has unnecessary/unsafe access to high-noise transformer module of the model which invalidates the ability to use low-noise stage only that was introduced in https://github.com/huggingface/diffusers/pull/12024

> https://github.com/huggingface/diffusers/blob/b59654544bbaf5c6040e670397351abe0e543a75/src/diffusers/pipelines/wan/pipeline_wan_vace.py#L339

fix is trivial, gather `transformer.config.patch_size[1]` from either either `transformer` or `transformer_2`, whichever is available.

### Reproduction

load `WanVACEPipeline` with low-noise stage only `transformer_2` and keep high-noise stage `transformer` as None.

### Logs

```shell
│C:\ai\sdnext\venv\Lib\site-packages\diffusers\pipelines\wan\pipeline_wan_vace.py:339 in check_inputs                  │
│                                                                                                                      │
│   338 │   ):                                                                                                         │
│❱  339 │   │   base = self.vae_scale_factor_spatial * self.transformer.config.patch_size[1]                           │
│   340 │   │   if height % base != 0 or width % base != 0:                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'config'
```

### System Info

diffusers main branch

### Who can help?

@yiyixuxu @sayakpaul @DN6

**Comment by DN6** [comment]
Closing since we merged #12428
