### ISSUE TITLE
IP Adapter Face ID community pipeline fails with AttributeError: 'tuple' object has no attribute 'shape' 

### ISSUE THREAD

**Issue by Woolverine94** [huggingface/diffusers#6832]
### Describe the bug

Hello Diffusers team and contributors,

Starting from commit 2e8d18e, the [IP Adapter Face ID](https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#ip-adapter-face-id) community pipeline stopped working and inference terminate during first iteration with the following error message : 
```bash
AttributeError: 'tuple' object has no attribute 'shape'
```
Reproducible with a slightly modified version (adaptation for cpu inference) of the documentation's example. 

Temporary workaround for this was a rollback to parent commit (03373de).

As this is a community pipeline, and recent commits seems to introduce similar features (like "instant LoRA"), I don't have strong expectations of this being fixed, but just want to alert on this error and thanks @fabiorigano for this very fun pipeline.

### Reproduction

```py
import diffusers
diffusers.utils.USE_PEFT_BACKEND = False
import torch
from diffusers.utils import load_image
import cv2
import numpy as np
from diffusers import DiffusionPipeline, AutoencoderKL, DDIMScheduler
from insightface.app import FaceAnalysis


noise_scheduler = DDIMScheduler(
    num_train_timesteps=1000,
    beta_start=0.00085,
    beta_end=0.012,
    beta_schedule="scaled_linear",
    clip_sample=False,
    set_alpha_to_one=False,
    steps_offset=1,
)
vae = AutoencoderKL.from_pretrained("stabilityai/sd-vae-ft-mse").to(dtype=torch.float32)
pipeline = DiffusionPipeline.from_pretrained(
    "SG161222/Realistic_Vision_V4.0_noVAE",
    torch_dtype=torch.float32,
    scheduler=noise_scheduler,
    vae=vae,
    custom_pipeline="ip_adapter_face_id"
)
pipeline.load_ip_adapter_face_id("h94/IP-Adapter-FaceID", "ip-adapter-faceid_sd15.bin")
pipeline.to("cpu")

generator = torch.Generator(device="cpu").manual_seed(42)
num_images=2

image = load_image("https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/ai_face2.png")

app = FaceAnalysis(name="buffalo_l", providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
app.prepare(ctx_id=0, det_size=(640, 640))
image = cv2.cvtColor(np.asarray(image), cv2.COLOR_BGR2RGB)
faces = app.get(image)
image = torch.from_numpy(faces[0].normed_embedding).unsqueeze(0)
images = pipeline(
    prompt="A photo of a girl wearing a black dress, holding red roses in hand, upper body, behind is the Eiffel Tower",
    image_embeds=image,
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality", 
    num_inference_steps=20, num_images_per_prompt=num_images, width=512, height=704, 
    generator=generator
).images

for i in range(num_images):
    images[i].save(f"c{i}.png")
```

### Logs

```shell
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1201 (you have 2.1.0+cpu)
    Python  3.11.6 (you have 3.11.2)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
/home/Woolverine94/biniou/env/lib/python3.11/site-packages/huggingface_hub/file_download.py:655: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Loading pipeline components...: 100%|█████████████| 5/5 [00:02<00:00,  2.42it/s]
/home/Woolverine94/biniou/env/lib/python3.11/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/Woolverine94/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/Woolverine94/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/Woolverine94/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/Woolverine94/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/Woolverine94/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/home/Woolverine94/biniou/env/lib/python3.11/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
  0%|                                                    | 0/20 [00:10<?, ?it/s]
Traceback (most recent call last):
  File "/home/Woolverine94/biniou/./test2.py", line 41, in <module>
    images = pipeline(
             ^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/.cache/huggingface/modules/diffusers_modules/git/ip_adapter_face_id.py", line 1464, in __call__
    noise_pred = self.unet(
                 ^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1121, in forward
    sample, res_samples = downsample_block(
                          ^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1199, in forward
    hidden_states = attn(
                    ^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/diffusers/models/transformers/transformer_2d.py", line 391, in forward
    hidden_states = block(
                    ^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/diffusers/models/attention.py", line 366, in forward
    attn_output = self.attn2(
                  ^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Woolverine94/biniou/env/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 512, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
  File "/home/Woolverine94/.cache/huggingface/modules/diffusers_modules/git/ip_adapter_face_id.py", line 246, in __call__
    hidden_states.shape if encoder_hidden_states is None else encoder_hidden_states.shape
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'shape'
```

### System Info

- `diffusers` version: 0.26.0.dev0 (any Diffusers version >= 2e8d18e, including 0.26.0 and 0.26.1)
- Platform: Linux-6.1.0-17-amd64-x86_64-with-glibc2.36
- Python version: 3.11.2
- PyTorch version (GPU?): 2.1.0+cpu (False)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.37.2
- Accelerate version: 0.26.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

@fabiorigano , @yiyixuxu

**Comment by asomoza** [comment]
this is actually a really easy fix, if @fabiorigano or @yiyixuxu don't have the time to do it, I can do it.

**Comment by fabiorigano** [comment]
hi @Woolverine94 thanks for reporting this bug, I will open a PR to fix it!

**Comment by Woolverine94** [comment]
Thanks a lot for this fast bugfix @fabiorigano ! 
I can confirm -if necessary- that calling this PR as a local community pipeline solved the reported issue.

**Comment by yiyixuxu** [comment]
merged!
thanks for spotting the bug, offering to help, and fixing the bug so quickly!

**Comment by Woolverine94** [comment]
Don't know if it worth re-opening the issue for that and even if it's related to this specific pipeline, but after upgrading Diffusers to 13001ee, and NOT using a local pipeline, the issue reappear.

After investigations, it appears that the file downloaded in `~/.cache/huggingface/modules/diffusers_modules/git/ip_adapter_face_id.py` was not the new PR (huggingface_hub bug ?).

Workaround is adding `custom_revision="main"` as an argument for .from_pretrained().
Removing it breaks everything again, like if default value for `custom_revision` was not `main`, as mentioned in the [documentation](https://huggingface.co/docs/diffusers/v0.26.1/en/api/pipelines/overview#diffusers.DiffusionPipeline.from_pretrained.custom_revision).

**Comment by fabiorigano** [comment]
Hi @Woolverine94 could you please try to load the custom_pipeline with the full path (e.g. custom_pipeline="/content/diffusers/examples/community/ip_adapter_face_id.py")?

It could be a problem of huggingface cache.

**Comment by yiyixuxu** [comment]
@cc @stevhliu here 

Yes I think we should update our doc (both the docstring https://huggingface.co/docs/diffusers/v0.26.1/en/api/pipelines/overview#diffusers.DiffusionPipeline.from_pretrained.custom_revision and the guide about loading community pipeline https://huggingface.co/docs/diffusers/using-diffusers/custom_pipeline_overview) 

* correct the docstring for `custom_revision` argument and make a note in the loading guide (see patrick's comment https://github.com/huggingface/diffusers/issues/6430#issuecomment-1878476945)
* maybe also talk about how to load a community pipeline from a local file by passing a file path instead
