### ISSUE TITLE
'UNet2DConditionModel' object has no attribute 'attn_processors' when using unet.set_attn_processor() after forward pass

### ISSUE THREAD

**Issue by LeggereZidrone** [huggingface/diffusers#6966]
### Describe the bug

Hi together,

I'm working on a usecase applying LoRA to a standard UNet2DConditionModel. I add LoRA as is done in the [example script](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/lora/train_text_to_image_lora.py):
```python
lora_attn_procs = {}
for name in unet.attn_processors.keys():
    cross_attention_dim = None if name.endswith("attn1.processor") else unet.config.cross_attention_dim
    if name.startswith("mid_block"):
        hidden_size = unet.config.block_out_channels[-1]
        elif name.startswith("up_blocks"):
            block_id = int(name[len("up_blocks.")])
            hidden_size = list(reversed(unet.config.block_out_channels))[block_id]
        elif name.startswith("down_blocks"):
            block_id = int(name[len("down_blocks.")])
            hidden_size = unet.config.block_out_channels[block_id]
    
    lora_attn_procs[name] = LoRAAttnProcessor(hidden_size=hidden_size, cross_attention_dim=cross_attention_dim)

unet.set_attn_processor(lora_attn_procs)
unet_lora_layers = AttnProcsLayers(unet.attn_processors)
```
Then I do a normal forward pass:
```python
...
model_pred = unet(noisy_model_input, timesteps, condition).sample
...
```

At this point, the ´unet.attn_processors´ is still accessible as normal.
However, if I now repeat the process and run `unet.set_attn_processor(lora_attn_procs)`, the assignment fails (?) and the unet afterwards does not have any attn_processors anymore:
```python
unet_lora_layers = AttnProcsLayers(unet.attn_processors)
>>> AttributeError: 'UNet2DConditionModel' object has no attribute 'attn_processors'
```

Notably, this worked on `0.17.1`, but does not work anymore after upgrading to a higher version - neither `0.23.1` nor `0.26.1`(in the latter, the LoRAAttnProcessor is deprecated, but the same thing happens even when I manually removed the deprecation warning).

It also seems like this has been mentioned before [here](https://github.com/huggingface/diffusers/issues/5441#issuecomment-1780857136). Would be glad to know if this is a bug or I'm doing something wrong. For now I can presumably stay on `0.17.1`, but it's not a permanent solution.

Thanks in advance!

### Reproduction

```python
def train_lora(
    pipe,
    image,
    condition,
    save_lora_dir,
    lora_steps=200,
    lora_lr=2e-4,
    lora_rank=16,
    weight_name=None,
    safe_serialization=False,
):
    # initialize accelerator
    accelerator = Accelerator(
        gradient_accumulation_steps=1,
        # mixed_precision='fp16'
    )
    set_seed(0)

    vae = pipe.vae
    unet = pipe.unet
    noise_scheduler = pipe.scheduler

    # set device and dtype
    device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")    

    lora_attn_procs = {}
    for name in unet.attn_processors.keys():
        cross_attention_dim = None if name.endswith("attn1.processor") else unet.config.cross_attention_dim
        if name.startswith("mid_block"):
            hidden_size = unet.config.block_out_channels[-1]
        elif name.startswith("up_blocks"):
            block_id = int(name[len("up_blocks.")])
            hidden_size = list(reversed(unet.config.block_out_channels))[block_id]
        elif name.startswith("down_blocks"):
            block_id = int(name[len("down_blocks.")])
            hidden_size = unet.config.block_out_channels[block_id]

        lora_attn_procs[name] = LoRAAttnProcessor(hidden_size=hidden_size, cross_attention_dim=cross_attention_dim)

    unet.set_attn_processor(lora_attn_procs)
    unet_lora_layers = AttnProcsLayers(unet.attn_processors)

    # Optimizer creation
    params_to_optimize = unet_lora_layers.parameters()
    optimizer = torch.optim.AdamW(params_to_optimize, lr=lora_lr, betas=(0.9, 0.999), weight_decay=1e-2, eps=1e-08)

    lr_scheduler = get_scheduler("constant", optimizer=optimizer, num_warmup_steps=0, num_training_steps=lora_steps, num_cycles=1, power=1.0)

    # prepare accelerator
    unet_lora_layers = accelerator.prepare_model(unet_lora_layers)
    optimizer = accelerator.prepare_optimizer(optimizer)
    lr_scheduler = accelerator.prepare_scheduler(lr_scheduler)

    if condition is None:
        # initialize condition
        raise NotImplementedError("Must provide a condition")
    else:
        condition = condition.to(device)

    if type(image) == np.ndarray:
        image = Image.fromarray(image)

    # initialize latent distribution
    image_transforms = transforms.Compose(
        [
            transforms.Resize(512, interpolation=transforms.InterpolationMode.BILINEAR),
            # transforms.RandomCrop(512),
            transforms.ToTensor(),
            transforms.Normalize([0.5], [0.5]),
        ]
    )

    image = image_transforms(image).to(device, torch.float16)
    image = image.unsqueeze(dim=0)
    latents_dist = vae.encode(image).latent_dist
    for _ in progress.tqdm(range(lora_steps), desc="Training LoRA..."):
        unet.train()
        model_input = latents_dist.sample() * vae.config.scaling_factor
        # Sample noise that we'll add to the latents
        noise = torch.randn_like(model_input)
        bsz, _channels, _height, _width = model_input.shape
        # Sample a random timestep for each image
        timesteps = torch.randint(0, noise_scheduler.config.num_train_timesteps, (bsz,), device=model_input.device)
        timesteps = timesteps.long()

        # Add noise to the model input according to the noise magnitude at each timestep
        # (this is the forward diffusion process)
        noisy_model_input = noise_scheduler.add_noise(model_input, noise, timesteps)
        # Predict the noise residual
        model_pred = unet(noisy_model_input, timesteps, condition).sample
```

### System Info

- `diffusers` version: 0.23.1
- Platform: Linux-5.10.0-27-cloud-amd64-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Huggingface_hub version: 0.20.3
- Transformers version: 4.37.2
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

 @DN6 @yiyixuxu @sayakpaul @patrickvonplaten

**Comment by sayakpaul** [comment]
You should use `peft` for this. https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py already provided a reference for that:

https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py#L844C1-L850C39

**Comment by yiyixuxu** [comment]
@sayakpaul 

Should we move `LoRAAttnProcessor` to a deprecated folder or something? https://github.com/huggingface/diffusers/blob/3a7e481611bc299416aaeed4207086d9ddca5852/src/diffusers/models/attention_processor.py#L1813

**Comment by sayakpaul** [comment]
I think we should just throw depcrecation warnings here following the standards. I will open a PR.
