### PR TITLE
[ONNX] Improve ONNXPipeline scheduler compatibility, fix safety_checker

### LINKED ISSUE #967: Schedulers not compatible with OnnxStableDiffusionPipeline: TypeError: unsupported operand
### Describe the bug

Hi,
I tried to use different schedulers with OnnxStableDiffusionPipeline, but it throw errors.
Schedulers are not compatible with numpy used in onnx pipeline.

Onnx checkpoints converted with: [convert_stable_diffusion_checkpoint_to_onnx.py](https://raw.githubusercontent.com/huggingface/diffusers/main/scripts/convert_stable_diffusion_checkpoint_to_onnx.py)

I have found a solution, but it is probably not optimal, because torch usage inside pipeline __call__.

Solution works with:
- `CompVis/stable-diffusion-v1-4`
- `hakurei/waifu-diffusion`

First error:
```
File "C:\...\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 152, in __call__
  latents = latents * self.scheduler.init_noise_sigma
TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Tensor'
```

If I cast latents to torch.tensor, before init_noise_sigma:
```py
latents = torch.tensor(latents)
latents = latents * self.scheduler.init_noise_sigma
```
```
File "C:\...\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 171, in __call__
  noise_pred = self.unet(
File "C:\...\diffusers\onnx_utils.py", line 46, in __call__
  return self.model.run(None, inputs)
File "C:\...\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
  return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(int64))
```

If I add dtype=np.int64 to timestep in unet args:
```py
# predict the noise residual
noise_pred = self.unet(
  sample=latent_model_input,
  timestep=np.array([t], dtype=np.int64),
  encoder_hidden_states=text_embeddings,
)
```
```
File "C:\...\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 184, in __call__
  latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
File "C:\...\diffusers\schedulers\scheduling_lms_discrete.py", line 224, in step
  pred_original_sample = sample - sigma * model_output
TypeError: unsupported operand type(s) for -: 'numpy.ndarray' and 'Tensor'
```

And if I cast latents to torch.tensor, before passing them into scheduler.step, it is working again:
```py
# compute the previous noisy sample x_t -> x_t-1
latents = torch.tensor(latents)
latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
latents = np.array(latents)
```

### Reproduction

```py
from diffusers import OnnxStableDiffusionPipeline, LMSDiscreteScheduler

lms = LMSDiscreteScheduler()

pipe = OnnxStableDiffusionPipeline.from_pretrained(
    model_path,
    provider="DmlExecutionProvider",
    scheduler=lms,
    local_files_only=True,
)

image = pipe("prompt")[0]
```

### Logs

_No response_

### System Info

- `diffusers` version: 0.6.0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.7
- PyTorch version (GPU?): 1.12.1+cpu (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: DmlExecutionProvider
- Using distributed or parallel set-up in script?: <fill in>

- GPU: AMD RX 6900 XT 16GB

### LINKED ISSUE #1138: safety_checker=None returns None is of type: <class 'NoneType'>, but should be <class 'diffusers.onnx_utils.OnnxRuntimeModel'> (OnnxStableDiffusionPipeline)
### Describe the bug

safety_checker=None is not accepted by OnnxStableDiffusionPipeline.from_pretrained due to how its passed to pipeline_utils.py

### Reproduction

```
pipe = OnnxStableDiffusionPipeline.from_pretrained(
    model,
    revision="onnx",
    provider="DmlExecutionProvider", 
    safety_checker=None
)
```

### Logs

```shell
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:

pip install accelerate

.
2022-11-04 09:24:39.2747512 [W:onnxruntime:, inference_session.cc:491 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider.
2022-11-04 09:24:39.4554147 [W:onnxruntime:, session_state.cc:1030 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2022-11-04 09:24:39.4610289 [W:onnxruntime:, session_state.cc:1032 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
Traceback (most recent call last):
  File "D:\ai\txt_to_img.py", line 56, in <module>
    pipe = OnnxStableDiffusionPipeline.from_pretrained(
  File "D:\ai\sd_env\lib\site-packages\diffusers\pipeline_utils.py", line 556, in from_pretrained
    raise ValueError(
ValueError: None is of type: <class 'NoneType'>, but should be <class 'diffusers.onnx_utils.OnnxRuntimeModel'>
```

### Workaround

After initializing OnnxStableDiffusionPipeline.from_pretrained call:

`pipe.safety_checker = None`

### System Info

- `diffusers` version: 0.7.1
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0+cpu (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: AMD RX580 via DmlExecutionProvider (onnxruntime-directml)

### PR DESCRIPTION
**Pull request by anton-l**
* Makes onnx pipelines compatible with DDIM and K-LMS (dtype fixes)
* Allows to set `safety_checker=None` for onnx pipelines. 

Fixes #967
Fixes #1138

### CODE REVIEW

File: src/diffusers/onnx_utils.py [hunk 1]
```diff
@@ -84,6 +99,15 @@ def _save_pretrained(self, save_directory: Union[str, Path], file_name: Optional
...
             pass
 
+        # copy external weights (for models >2GB)
+        src_path = self.model_save_dir.joinpath(ONNX_EXTERNAL_WEIGHTS_NAME)
+        if src_path.exists():
+            dst_path = Path(save_directory).joinpath(ONNX_EXTERNAL_WEIGHTS_NAME)
+            try:
+                shutil.copyfile(src_path, dst_path)
+            except shutil.SameFileError:
+                pass
```
Comment (anton-l) [inline src/diffusers/onnx_utils.py:109]: The external `weights.pb` wasn't copied before, breaking `from_pretrained` after `save_pretrained`

File: src/diffusers/pipeline_utils.py [hunk 2]
```diff
@@ -541,7 +541,7 @@ def from_pretrained(cls, pretrained_model_name_or_path: Optional[Union[str, os.P
             # if the model is in a pipeline module, then we load it from the pipeline
             if name in passed_class_obj:
                 # 1. check that passed_class_obj has correct parent class
-                if not is_pipeline_module:
+                if not is_pipeline_module and passed_class_obj[name] is not None:
```
Comment (anton-l) [inline src/diffusers/pipeline_utils.py:544]: Since `safety_checker` is `OnnxRuntimeModel` and not a pipeline module like in the pytorch version, it produced an error further in this branch when `safety_checker==None`. 
So let's just skip anything that's `None` here.

File: src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py [hunk 3]
```diff
@@ -197,15 +198,20 @@ def __call__(
         if accepts_eta:
             extra_step_kwargs["eta"] = eta
 
+        timestep_dtype = next(
+            (input.type for input in self.unet.model.get_inputs() if input.name == "timestep"), "tensor(float)"
+        )
+        timestep_dtype = ORT_TO_NP_TYPE[timestep_dtype]
```
Comment (anton-l) [inline src/diffusers/pipelines/stable_diffusion/pipeline_onnx_stable_diffusion.py:204]: Passing float timesteps (as in K-LMS) to the onnx unet will result in a type error. This adds a bit of back-compatibility until we update checkpoints to accept `float` timesteps.

(Can't change them to `float` right away, that will break pipelines from older version of `diffusers`)

File: src/diffusers/pipeline_utils.py (hunk 2 above)
Comment (patrickvonplaten) [reply src/diffusers/pipeline_utils.py:544]: ok!

**Review by patrickvonplaten — APPROVED** [review]
Cool, looks good to me!

**Comment by kleiti** [comment]
#1083 Still seems to apply after these changes, safety_check=None can be set now - output still looks to be black with DmlExecutionProvider. Did re-convert the models using the new convert_stable_diffusion_checkpoint_to_onnx.py.

**Comment by anton-l** [comment]
@kleiti thank you for checking! Let's keep that issue open then, until we get a DirectML setup to debug

**Review by pcuenca — APPROVED** [review]
Works fine for me!

One thing that I noticed that is unrelated to this PR is that `StableDiffusionOnnxPipeline` no longer works (it's deprecated until `1.0.0`), I think it broke in #552. I'll push a PR for discussion shortly.

**Comment by GreenLandisaLie** [comment]
Can you add compatibility with EulerA? I haven't tested yet but the (normal) Euler scheduler probably also doesn't work.

I get: "AttributeError: 'numpy.ndarray' object has no attribute 'device'" when it runs the code:
latents = self.scheduler.step(noise_pred, t, torch.from_numpy(latents), **extra_step_kwargs).prev_sample


One thing I've noticed is the (normal) SD pipeline checks if the scheduler accepts a generator and if so it is passed with **extra_step_kwargs - but ONNX doesn't do that even though DDIM does accept a generator. Is that intentional?

Thank you for everything you have done so far! I wouldn't be able to enjoy Stable Diffusion without ONNX support atm.
